name: UnrealEngine
summary:  game engine. 
description: the most powerful creation engine.
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: i386
  - build-on: amd64
  

apps:
  UnrealEngine:
    command: bin/UnrealEngine
    plugs:
      - home
      - network
      - removable-media

parts:
UnrealEngine:
    plugin: 
    source: https://github.com/EpicGames/UnrealEngine.git
    source-type: git
    override-pull: |
     git clone https://github.com/EpicGames/UnrealEngine.git src/github.com/EpicGames/UnrealEngine
       cd src/github.com/EpicGames/UnrealEngine
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/EpicGames/UnrealEngine
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/EpicGames/UnrealEngine/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/EpicGames/UnrealEngine/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/UnrealEngine
    build-snaps:
      - 
    build-packages:
      - git
      - sed
